# Generated by Django 5.1.2 on 2024-10-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_horario_delete_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='domingo',
            new_name='domingo_diurno',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='quarta',
            new_name='domingo_noturno',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='quinta',
            new_name='quarta_diurno',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='sabado',
            new_name='quarta_noturno',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='segunda',
            new_name='quinta_diurno',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='sexta',
            new_name='quinta_noturno',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='terca',
            new_name='sabado_diurno',
        ),
        migrations.AddField(
            model_name='horario',
            name='sabado_noturno',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='segunda_diurno',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='segunda_noturno',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='sexta_diurno',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='sexta_noturno',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='terca_diurno',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='terca_noturno',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
