# Generated by Django 5.1.2 on 2024-10-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_rename_domingo_horario_domingo_diurno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='address',
            new_name='bairro',
        ),
        migrations.AddField(
            model_name='horario',
            name='cidade',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='estado',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='logradouro',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
