# Generated by Django 5.1.2 on 2024-10-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_rename_address_horario_bairro_horario_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='estado',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
